name: test_gridview
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_staggered_grid_view: ^0.6.1
  get: ^4.6.5
  native_flutter_proxy: ^0.1.15
  fair_widget:
    git:
      url: git@igit.58corp.com:fair/fair_widget.git
      ref: 'master'

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



dependency_overrides:
  collection: 1.17.0
  fair_version: 3.3.0

  fair:
    git:
      url: https://github.com/wuba/fair.git
      ref: main
      path: fair

flutter:

  uses-material-design: true
